repos:
-   repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    - id: black
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
    - id: pyupgrade
      args: [--keep-percent-format]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
